on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TypeStrong/typedoc-action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
